quotestoscrape:
  base:
    url: http://quotes.toscrape.com/
    path:
      - body > div > div:nth-child(2) > div.col-md-4.tags-box > span > a
  content:
    quote:
      path:
        - body > div > div:nth-child(3) > div.col-md-8 > div > span:nth-child(1)
      terminator: null
    author:
      path:
        - body > div > div:nth-child(3) > div.col-md-8 > div > span:nth-child(2)


<YOUR_SECOND_VENDOR_NAME>:
  base:
    url: <URL_OF_THE_SITE_FROM-WHERE_YOU_WANT_TO_EXTRACT_ALL_URLS>
    path:
      - <PATH_TO_SINGLE_URL_ELEMENT>
  content:
    <CONTENT_SECTION_1>:
      path:
        - <YOUR_CSS_SELECTOR_PATH>
    <CONTENT_SECTION_2>:
      path:
        - <YOUR_CSS_SELECTOR_PATH>
      terminator: <YOUR_CSS_SELECTOR_PATH_TO_TERMINATING_POINT>
    <CONTENT_SECTION_n>:
      path:
        - <YOUR_CSS_SELECTOR_PATH_1>
        - <YOUR_CSS_SELECTOR_PATH_2>
      terminator: <YOUR_CSS_SELECTOR_PATH_TO_TERMINATING_POINT>
